# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'KS_inke' do
pod 'AFNetworking'
pod 'SDWebImage'
pod 'Masonry'
pod 'YYKit'
pod 'MJExtension'
pod 'LFLiveKit'

end

target 'KS_inkeTests' do

end

target 'KS_inkeUITests' do

end

